package plugin

import (
	"github.com/tx7do/go-wind-toolkit/protoc-gen-dart-http/internal/codegen"
	"github.com/tx7do/go-wind-toolkit/protoc-gen-dart-http/internal/protowalk"
	"google.golang.org/protobuf/reflect/protoreflect"
)

type packageGenerator struct {
	pkg   protoreflect.FullName
	files []protoreflect.FileDescriptor
}

func (p packageGenerator) Generate(f *codegen.File) error {
	p.generateHeader(f)
	hasServices := p.hasServices()

	// Conditionally add imports only when the package has services.
	if hasServices {
		f.P("import 'dart:async';")
		f.P("import 'dart:convert';")
	}
	f.P("import '", transportImportPath(p.pkg), "';")
	f.P()

	// defaultHost constant (only if there are services and a host is set).
	defaultHost := p.readDefaultHost()
	if hasServices && defaultHost != "" {
		f.P("const defaultHost = ", dartString(defaultHost), ";")
		f.P()
	}

	var walkErr error
	var services []protoreflect.ServiceDescriptor
	protowalk.WalkFiles(p.files, func(desc protoreflect.Descriptor) bool {
		if wkt, ok := WellKnownType(desc); ok {
			f.P(wkt.TypeDeclaration())
			return false
		}
		switch v := desc.(type) {
		case protoreflect.MessageDescriptor:
			if v.IsMapEntry() {
				return false
			}
			messageGenerator{pkg: p.pkg, message: v}.Generate(f)
		case protoreflect.EnumDescriptor:
			enumGenerator{pkg: p.pkg, enum: v}.Generate(f)
		case protoreflect.ServiceDescriptor:
			services = append(services, v)
			if err := (serviceGenerator{
				pkg:     p.pkg,
				service: v,
			}).Generate(f); err != nil {
				walkErr = err
				return false
			}
		}
		return true
	})
	if walkErr != nil {
		return walkErr
	}
	// Generate the unified ApiClient after all individual service clients.
	generateApiClient(f, services)
	return nil
}

func (p packageGenerator) readDefaultHost() string {
	var firstHost string
	var firstService string
	for _, file := range p.files {
		services := file.Services()
		for i := 0; i < services.Len(); i++ {
			svc := services.Get(i)
			host := getDefaultHost(svc)
			if host == "" {
				continue
			}
			if firstHost == "" {
				firstHost = host
				firstService = string(svc.FullName())
			} else if host != firstHost {
				Warn("service %s has default_host %q but service %s already set %q; using the first one", svc.FullName(), host, firstService, firstHost)
			}
		}
	}
	return firstHost
}

func (p packageGenerator) generateHeader(f *codegen.File) {
	f.P("// Code generated by protoc-gen-dart-http. DO NOT EDIT.")
	f.P()
	f.P("// ignore_for_file: unused_import, unnecessary_cast, avoid_print, non_constant_identifier_names, avoid_equals_and_hash_code_on_mutable_classes")
	f.P()
}

// hasServices returns true if any file in the package declares a service.
func (p packageGenerator) hasServices() bool {
	for _, file := range p.files {
		if file.Services().Len() > 0 {
			return true
		}
	}
	return false
}
