// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: examples/user/pb/user.proto

package pb

import (
	_ "github.com/tx7do/go-wind-toolkit/protoc-gen-go-redact/redact/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User credentials
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // default redaction
	// User information
	Email         string         `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name          string         `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Home          *User_Location `protobuf:"bytes,5,opt,name=home,proto3" json:"home,omitempty"`
	Opt           string         `protobuf:"bytes,6,opt,name=opt,proto3" json:"opt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_examples_user_pb_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_examples_user_pb_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_examples_user_pb_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetHome() *User_Location {
	if x != nil {
		return x.Home
	}
	return nil
}

func (x *User) GetOpt() string {
	if x != nil {
		return x.Opt
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_examples_user_pb_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_user_pb_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_examples_user_pb_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_examples_user_pb_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_user_pb_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_examples_user_pb_user_proto_rawDescGZIP(), []int{2}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type User_Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_Location) Reset() {
	*x = User_Location{}
	mi := &file_examples_user_pb_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Location) ProtoMessage() {}

func (x *User_Location) ProtoReflect() protoreflect.Message {
	mi := &file_examples_user_pb_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Location.ProtoReflect.Descriptor instead.
func (*User_Location) Descriptor() ([]byte, []int) {
	return file_examples_user_pb_user_proto_rawDescGZIP(), []int{0, 0}
}

func (x *User_Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *User_Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

var File_examples_user_pb_user_proto protoreflect.FileDescriptor

const file_examples_user_pb_user_proto_rawDesc = "" +
	"\n" +
	"\x1bexamples/user/pb/user.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16redact/v1/redact.proto\"\xeb\x01\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\"\n" +
	"\bpassword\x18\x02 \x01(\tB\x06ڶ\x1a\x02z\x00R\bpassword\x12$\n" +
	"\x05email\x18\x03 \x01(\tB\x0eڶ\x1a\n" +
	"z\br*d@ct*dR\x05email\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12'\n" +
	"\x04home\x18\x05 \x01(\v2\x13.user.User.LocationR\x04home\x12\x10\n" +
	"\x03opt\x18\x06 \x01(\tR\x03opt\x1a.\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\",\n" +
	"\x0eGetUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"5\n" +
	"\x11ListUsersResponse\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".user.UserR\x05users2\xc8\x01\n" +
	"\x04Chat\x12'\n" +
	"\aAddUser\x12\n" +
	".user.User\x1a\n" +
	".user.User\"\x04\xe0\xb6\x1a\x01\x12-\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\n" +
	".user.User\"\x00\x12h\n" +
	"\tListUsers\x12\x16.google.protobuf.Empty\x1a\x17.user.ListUsersResponse\"*\xe0\xb6\x1a\x01\xe8\xb6\x1a\x0e\xf2\xb6\x1a\x1e%service%.%method% unavailableBKZIgithub.com/tx7do/go-wind-toolkit/protoc-gen-go-redact/examples/user/pb;pbb\x06proto3"

var (
	file_examples_user_pb_user_proto_rawDescOnce sync.Once
	file_examples_user_pb_user_proto_rawDescData []byte
)

func file_examples_user_pb_user_proto_rawDescGZIP() []byte {
	file_examples_user_pb_user_proto_rawDescOnce.Do(func() {
		file_examples_user_pb_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_user_pb_user_proto_rawDesc), len(file_examples_user_pb_user_proto_rawDesc)))
	})
	return file_examples_user_pb_user_proto_rawDescData
}

var file_examples_user_pb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_examples_user_pb_user_proto_goTypes = []any{
	(*User)(nil),              // 0: user.User
	(*GetUserRequest)(nil),    // 1: user.GetUserRequest
	(*ListUsersResponse)(nil), // 2: user.ListUsersResponse
	(*User_Location)(nil),     // 3: user.User.Location
	(*emptypb.Empty)(nil),     // 4: google.protobuf.Empty
}
var file_examples_user_pb_user_proto_depIdxs = []int32{
	3, // 0: user.User.home:type_name -> user.User.Location
	0, // 1: user.ListUsersResponse.users:type_name -> user.User
	0, // 2: user.Chat.AddUser:input_type -> user.User
	1, // 3: user.Chat.GetUser:input_type -> user.GetUserRequest
	4, // 4: user.Chat.ListUsers:input_type -> google.protobuf.Empty
	0, // 5: user.Chat.AddUser:output_type -> user.User
	0, // 6: user.Chat.GetUser:output_type -> user.User
	2, // 7: user.Chat.ListUsers:output_type -> user.ListUsersResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_examples_user_pb_user_proto_init() }
func file_examples_user_pb_user_proto_init() {
	if File_examples_user_pb_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_user_pb_user_proto_rawDesc), len(file_examples_user_pb_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_user_pb_user_proto_goTypes,
		DependencyIndexes: file_examples_user_pb_user_proto_depIdxs,
		MessageInfos:      file_examples_user_pb_user_proto_msgTypes,
	}.Build()
	File_examples_user_pb_user_proto = out.File
	file_examples_user_pb_user_proto_goTypes = nil
	file_examples_user_pb_user_proto_depIdxs = nil
}
