// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: redact/v3/redact.proto

// Package redact provides interfaces and methods to help implement redaction.

package redact

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldRules encapsulates options to change the redacted values of any type of field.
// Depending on the field, the correct type value should be used.
type FieldRules struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// values for redacted field
	//
	// Types that are valid to be assigned to Values:
	//
	//	*FieldRules_Float
	//	*FieldRules_Double
	//	*FieldRules_Int32
	//	*FieldRules_Int64
	//	*FieldRules_Uint32
	//	*FieldRules_Uint64
	//	*FieldRules_Sint32
	//	*FieldRules_Sint64
	//	*FieldRules_Fixed32
	//	*FieldRules_Fixed64
	//	*FieldRules_Sfixed32
	//	*FieldRules_Sfixed64
	//	*FieldRules_Bool
	//	*FieldRules_String_
	//	*FieldRules_Bytes
	//	*FieldRules_Enum
	//	*FieldRules_Message
	//	*FieldRules_Element
	//	*FieldRules_Regex
	Values        isFieldRules_Values `protobuf_oneof:"values"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldRules) Reset() {
	*x = FieldRules{}
	mi := &file_redact_v3_redact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldRules) ProtoMessage() {}

func (x *FieldRules) ProtoReflect() protoreflect.Message {
	mi := &file_redact_v3_redact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldRules.ProtoReflect.Descriptor instead.
func (*FieldRules) Descriptor() ([]byte, []int) {
	return file_redact_v3_redact_proto_rawDescGZIP(), []int{0}
}

func (x *FieldRules) GetValues() isFieldRules_Values {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *FieldRules) GetFloat() float32 {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Float); ok {
			return x.Float
		}
	}
	return 0
}

func (x *FieldRules) GetDouble() float64 {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Double); ok {
			return x.Double
		}
	}
	return 0
}

func (x *FieldRules) GetInt32() int32 {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Int32); ok {
			return x.Int32
		}
	}
	return 0
}

func (x *FieldRules) GetInt64() int64 {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Int64); ok {
			return x.Int64
		}
	}
	return 0
}

func (x *FieldRules) GetUint32() uint32 {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Uint32); ok {
			return x.Uint32
		}
	}
	return 0
}

func (x *FieldRules) GetUint64() uint64 {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Uint64); ok {
			return x.Uint64
		}
	}
	return 0
}

func (x *FieldRules) GetSint32() int32 {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Sint32); ok {
			return x.Sint32
		}
	}
	return 0
}

func (x *FieldRules) GetSint64() int64 {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Sint64); ok {
			return x.Sint64
		}
	}
	return 0
}

func (x *FieldRules) GetFixed32() uint32 {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Fixed32); ok {
			return x.Fixed32
		}
	}
	return 0
}

func (x *FieldRules) GetFixed64() uint64 {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Fixed64); ok {
			return x.Fixed64
		}
	}
	return 0
}

func (x *FieldRules) GetSfixed32() int32 {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Sfixed32); ok {
			return x.Sfixed32
		}
	}
	return 0
}

func (x *FieldRules) GetSfixed64() int64 {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Sfixed64); ok {
			return x.Sfixed64
		}
	}
	return 0
}

func (x *FieldRules) GetBool() bool {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *FieldRules) GetString_() string {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *FieldRules) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *FieldRules) GetEnum() int32 {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Enum); ok {
			return x.Enum
		}
	}
	return 0
}

func (x *FieldRules) GetMessage() *MessageRules {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *FieldRules) GetElement() *ElementRules {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Element); ok {
			return x.Element
		}
	}
	return nil
}

func (x *FieldRules) GetRegex() *RegexRules {
	if x != nil {
		if x, ok := x.Values.(*FieldRules_Regex); ok {
			return x.Regex
		}
	}
	return nil
}

type isFieldRules_Values interface {
	isFieldRules_Values()
}

type FieldRules_Float struct {
	// Scalar Field Types values
	Float float32 `protobuf:"fixed32,2,opt,name=float,proto3,oneof"`
}

type FieldRules_Double struct {
	Double float64 `protobuf:"fixed64,3,opt,name=double,proto3,oneof"`
}

type FieldRules_Int32 struct {
	Int32 int32 `protobuf:"varint,4,opt,name=int32,proto3,oneof"`
}

type FieldRules_Int64 struct {
	Int64 int64 `protobuf:"varint,5,opt,name=int64,proto3,oneof"`
}

type FieldRules_Uint32 struct {
	Uint32 uint32 `protobuf:"varint,6,opt,name=uint32,proto3,oneof"`
}

type FieldRules_Uint64 struct {
	Uint64 uint64 `protobuf:"varint,7,opt,name=uint64,proto3,oneof"`
}

type FieldRules_Sint32 struct {
	Sint32 int32 `protobuf:"zigzag32,8,opt,name=sint32,proto3,oneof"`
}

type FieldRules_Sint64 struct {
	Sint64 int64 `protobuf:"zigzag64,9,opt,name=sint64,proto3,oneof"`
}

type FieldRules_Fixed32 struct {
	Fixed32 uint32 `protobuf:"fixed32,10,opt,name=fixed32,proto3,oneof"`
}

type FieldRules_Fixed64 struct {
	Fixed64 uint64 `protobuf:"fixed64,11,opt,name=fixed64,proto3,oneof"`
}

type FieldRules_Sfixed32 struct {
	Sfixed32 int32 `protobuf:"fixed32,12,opt,name=sfixed32,proto3,oneof"`
}

type FieldRules_Sfixed64 struct {
	Sfixed64 int64 `protobuf:"fixed64,13,opt,name=sfixed64,proto3,oneof"`
}

type FieldRules_Bool struct {
	Bool bool `protobuf:"varint,14,opt,name=bool,proto3,oneof"`
}

type FieldRules_String_ struct {
	String_ string `protobuf:"bytes,15,opt,name=string,proto3,oneof"`
}

type FieldRules_Bytes struct {
	Bytes []byte `protobuf:"bytes,16,opt,name=bytes,proto3,oneof"`
}

type FieldRules_Enum struct {
	Enum int32 `protobuf:"varint,17,opt,name=enum,proto3,oneof"`
}

type FieldRules_Message struct {
	// Message defines rules for singular message type fields only
	Message *MessageRules `protobuf:"bytes,19,opt,name=message,proto3,oneof"`
}

type FieldRules_Element struct {
	// Element defines rules for repeated or map type fields
	Element *ElementRules `protobuf:"bytes,20,opt,name=element,proto3,oneof"`
}

type FieldRules_Regex struct {
	// Regex defines regex-based masking for string fields (e.g. phone: 138****8888)
	Regex *RegexRules `protobuf:"bytes,21,opt,name=regex,proto3,oneof"`
}

func (*FieldRules_Float) isFieldRules_Values() {}

func (*FieldRules_Double) isFieldRules_Values() {}

func (*FieldRules_Int32) isFieldRules_Values() {}

func (*FieldRules_Int64) isFieldRules_Values() {}

func (*FieldRules_Uint32) isFieldRules_Values() {}

func (*FieldRules_Uint64) isFieldRules_Values() {}

func (*FieldRules_Sint32) isFieldRules_Values() {}

func (*FieldRules_Sint64) isFieldRules_Values() {}

func (*FieldRules_Fixed32) isFieldRules_Values() {}

func (*FieldRules_Fixed64) isFieldRules_Values() {}

func (*FieldRules_Sfixed32) isFieldRules_Values() {}

func (*FieldRules_Sfixed64) isFieldRules_Values() {}

func (*FieldRules_Bool) isFieldRules_Values() {}

func (*FieldRules_String_) isFieldRules_Values() {}

func (*FieldRules_Bytes) isFieldRules_Values() {}

func (*FieldRules_Enum) isFieldRules_Values() {}

func (*FieldRules_Message) isFieldRules_Values() {}

func (*FieldRules_Element) isFieldRules_Values() {}

func (*FieldRules_Regex) isFieldRules_Values() {}

// RegexRules describe regex-based partial masking for string fields.
// The regex pattern is compiled at package init time and applied via
// regexp.ReplaceAllString at redaction time.
type RegexRules struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pattern is the regular expression (RE2 syntax) to match against
	// the field value. Capture groups can be referenced in Replacement
	// via ${1}, ${2}, etc.
	Pattern string `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// Replacement is the replacement string. Use ${1}, ${2}, etc. to
	// reference captured groups. For example:
	//
	//	pattern:      "^(\\d{3})\\d{4}(\\d{4})$"
	//	replacement:  "${1}****${2}"
	//	13812345678 -> 138****5678
	Replacement   string `protobuf:"bytes,2,opt,name=replacement,proto3" json:"replacement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegexRules) Reset() {
	*x = RegexRules{}
	mi := &file_redact_v3_redact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegexRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegexRules) ProtoMessage() {}

func (x *RegexRules) ProtoReflect() protoreflect.Message {
	mi := &file_redact_v3_redact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegexRules.ProtoReflect.Descriptor instead.
func (*RegexRules) Descriptor() ([]byte, []int) {
	return file_redact_v3_redact_proto_rawDescGZIP(), []int{1}
}

func (x *RegexRules) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *RegexRules) GetReplacement() string {
	if x != nil {
		return x.Replacement
	}
	return ""
}

// MessageRules describe the constraints applied to embedded message for redaction.
// For message-type fields, rules are performed recursively.
type MessageRules struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Skip specifies that the redaction rules of this field should not be evaluated
	Skip bool `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	// Empty specifies that after redaction this field should be set to empty object
	Empty bool `protobuf:"varint,2,opt,name=empty,proto3" json:"empty,omitempty"`
	// Nil specifies that after redaction this field should be set to nil object
	Nil bool `protobuf:"varint,3,opt,name=nil,proto3" json:"nil,omitempty"`
	// Apply specifies that redaction is to be called for the message type
	Apply         bool `protobuf:"varint,4,opt,name=apply,proto3" json:"apply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRules) Reset() {
	*x = MessageRules{}
	mi := &file_redact_v3_redact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRules) ProtoMessage() {}

func (x *MessageRules) ProtoReflect() protoreflect.Message {
	mi := &file_redact_v3_redact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRules.ProtoReflect.Descriptor instead.
func (*MessageRules) Descriptor() ([]byte, []int) {
	return file_redact_v3_redact_proto_rawDescGZIP(), []int{2}
}

func (x *MessageRules) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *MessageRules) GetEmpty() bool {
	if x != nil {
		return x.Empty
	}
	return false
}

func (x *MessageRules) GetNil() bool {
	if x != nil {
		return x.Nil
	}
	return false
}

func (x *MessageRules) GetApply() bool {
	if x != nil {
		return x.Apply
	}
	return false
}

// ElementRules describe the constraints applied to `repeated` or `map` values
type ElementRules struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty specifies that after redaction the list/map will be empty
	Empty bool `protobuf:"varint,1,opt,name=empty,proto3" json:"empty,omitempty"`
	// Nested specifies that default rules is to be applied `recursively` on each
	// item of map/list
	Nested bool `protobuf:"varint,2,opt,name=nested,proto3" json:"nested,omitempty"`
	// Item specifies that some custom redaction rules to be applied `recursively`
	// on each item in map/list.
	Item          *FieldRules `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElementRules) Reset() {
	*x = ElementRules{}
	mi := &file_redact_v3_redact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElementRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementRules) ProtoMessage() {}

func (x *ElementRules) ProtoReflect() protoreflect.Message {
	mi := &file_redact_v3_redact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementRules.ProtoReflect.Descriptor instead.
func (*ElementRules) Descriptor() ([]byte, []int) {
	return file_redact_v3_redact_proto_rawDescGZIP(), []int{3}
}

func (x *ElementRules) GetEmpty() bool {
	if x != nil {
		return x.Empty
	}
	return false
}

func (x *ElementRules) GetNested() bool {
	if x != nil {
		return x.Nested
	}
	return false
}

func (x *ElementRules) GetItem() *FieldRules {
	if x != nil {
		return x.Item
	}
	return nil
}

var file_redact_v3_redact_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         90102,
		Name:          "redact.v3.file_skip",
		Tag:           "varint,90102,opt,name=file_skip",
		Filename:      "redact/v3/redact.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         54123,
		Name:          "redact.v3.service_skip",
		Tag:           "varint,54123,opt,name=service_skip",
		Filename:      "redact/v3/redact.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         54124,
		Name:          "redact.v3.internal_service",
		Tag:           "varint,54124,opt,name=internal_service",
		Filename:      "redact/v3/redact.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         54125,
		Name:          "redact.v3.internal_service_code",
		Tag:           "varint,54125,opt,name=internal_service_code",
		Filename:      "redact/v3/redact.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         54126,
		Name:          "redact.v3.internal_service_err_message",
		Tag:           "bytes,54126,opt,name=internal_service_err_message",
		Filename:      "redact/v3/redact.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         54123,
		Name:          "redact.v3.method_skip",
		Tag:           "varint,54123,opt,name=method_skip",
		Filename:      "redact/v3/redact.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         54124,
		Name:          "redact.v3.internal_method",
		Tag:           "varint,54124,opt,name=internal_method",
		Filename:      "redact/v3/redact.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         54125,
		Name:          "redact.v3.internal_method_code",
		Tag:           "varint,54125,opt,name=internal_method_code",
		Filename:      "redact/v3/redact.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         54126,
		Name:          "redact.v3.internal_method_err_message",
		Tag:           "bytes,54126,opt,name=internal_method_err_message",
		Filename:      "redact/v3/redact.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         54123,
		Name:          "redact.v3.nil",
		Tag:           "varint,54123,opt,name=nil",
		Filename:      "redact/v3/redact.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         54124,
		Name:          "redact.v3.empty",
		Tag:           "varint,54124,opt,name=empty",
		Filename:      "redact/v3/redact.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         54125,
		Name:          "redact.v3.ignored",
		Tag:           "varint,54125,opt,name=ignored",
		Filename:      "redact/v3/redact.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldRules)(nil),
		Field:         54123,
		Name:          "redact.v3.value",
		Tag:           "bytes,54123,opt,name=value",
		Filename:      "redact/v3/redact.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// FileSkip is used to skip generation of any redaction for proto file
	//
	// optional bool file_skip = 90102;
	E_FileSkip = &file_redact_v3_redact_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// ServiceSkip is used to skip the redaction in grpc service in the server
	//
	// optional bool service_skip = 54123;
	E_ServiceSkip = &file_redact_v3_redact_proto_extTypes[1]
	// InternalService will make this service private and client will not be
	// able to receive any response for any of it's method, (unless skipped
	// explicitly) and will get PermissionDenied(7) error by default, to set
	// any other code set it in InternalServiceCode, it should be one of the
	// defined GRPC status code, and InternalServiceErrMessage for error
	// message, in which, one can use `%service%` or `%method%` tags to include
	// corresponding service name or method name, respectively.
	//
	// optional bool internal_service = 54124;
	E_InternalService = &file_redact_v3_redact_proto_extTypes[2]
	// optional uint32 internal_service_code = 54125;
	E_InternalServiceCode = &file_redact_v3_redact_proto_extTypes[3]
	// optional string internal_service_err_message = 54126;
	E_InternalServiceErrMessage = &file_redact_v3_redact_proto_extTypes[4]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// MethodSkip is used to skip the redactions for this method in the grpc server
	//
	// optional bool method_skip = 54123;
	E_MethodSkip = &file_redact_v3_redact_proto_extTypes[5]
	// InternalMethod, InternalMethodCode and InternalMethodErrMessage works same
	// as that of service level options: InternalService, InternalServiceCode and
	// InternalServiceErrMessage, but at Method level. All the validations and
	// functionalities are same for both. But the method level options will be used
	// whenever both are specified.
	//
	// optional bool internal_method = 54124;
	E_InternalMethod = &file_redact_v3_redact_proto_extTypes[6]
	// optional uint32 internal_method_code = 54125;
	E_InternalMethodCode = &file_redact_v3_redact_proto_extTypes[7]
	// optional string internal_method_err_message = 54126;
	E_InternalMethodErrMessage = &file_redact_v3_redact_proto_extTypes[8]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// Nil will redact message to nil (can be override by field level, `empty` option)
	//
	// optional bool nil = 54123;
	E_Nil = &file_redact_v3_redact_proto_extTypes[9]
	// Empty will redact message to it's empty object
	//
	// optional bool empty = 54124;
	E_Empty = &file_redact_v3_redact_proto_extTypes[10]
	// Ignored skips generation of any redaction for this message.
	//
	// optional bool ignored = 54125;
	E_Ignored = &file_redact_v3_redact_proto_extTypes[11]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Redact: it redact the field with predefined defaults:
	//   - `0` for any number type
	//   - `"REDACTED"` for string type
	//   - `nil` for byte type
	//   - `0th value` for enum type
	//   - `nil` map for map type
	//   - `nil` for repeated field type
	//   - for message type, redaction is applied inside the message type
	//
	// bool redact = 54123;
	// Custom: specify the different values to be used for redaction on this field. By
	// default, if Custom value is not defined Redact should be true to apply redaction.
	// And if Custom value is to be assigned, one can skip the Redact field.
	//
	// optional redact.v3.FieldRules value = 54123;
	E_Value = &file_redact_v3_redact_proto_extTypes[12]
)

var File_redact_v3_redact_proto protoreflect.FileDescriptor

const file_redact_v3_redact_proto_rawDesc = "" +
	"\n" +
	"\x16redact/v3/redact.proto\x12\tredact.v3\x1a google/protobuf/descriptor.proto\"\xcb\x04\n" +
	"\n" +
	"FieldRules\x12\x16\n" +
	"\x05float\x18\x02 \x01(\x02H\x00R\x05float\x12\x18\n" +
	"\x06double\x18\x03 \x01(\x01H\x00R\x06double\x12\x16\n" +
	"\x05int32\x18\x04 \x01(\x05H\x00R\x05int32\x12\x16\n" +
	"\x05int64\x18\x05 \x01(\x03H\x00R\x05int64\x12\x18\n" +
	"\x06uint32\x18\x06 \x01(\rH\x00R\x06uint32\x12\x18\n" +
	"\x06uint64\x18\a \x01(\x04H\x00R\x06uint64\x12\x18\n" +
	"\x06sint32\x18\b \x01(\x11H\x00R\x06sint32\x12\x18\n" +
	"\x06sint64\x18\t \x01(\x12H\x00R\x06sint64\x12\x1a\n" +
	"\afixed32\x18\n" +
	" \x01(\aH\x00R\afixed32\x12\x1a\n" +
	"\afixed64\x18\v \x01(\x06H\x00R\afixed64\x12\x1c\n" +
	"\bsfixed32\x18\f \x01(\x0fH\x00R\bsfixed32\x12\x1c\n" +
	"\bsfixed64\x18\r \x01(\x10H\x00R\bsfixed64\x12\x14\n" +
	"\x04bool\x18\x0e \x01(\bH\x00R\x04bool\x12\x18\n" +
	"\x06string\x18\x0f \x01(\tH\x00R\x06string\x12\x16\n" +
	"\x05bytes\x18\x10 \x01(\fH\x00R\x05bytes\x12\x14\n" +
	"\x04enum\x18\x11 \x01(\x05H\x00R\x04enum\x123\n" +
	"\amessage\x18\x13 \x01(\v2\x17.redact.v3.MessageRulesH\x00R\amessage\x123\n" +
	"\aelement\x18\x14 \x01(\v2\x17.redact.v3.ElementRulesH\x00R\aelement\x12-\n" +
	"\x05regex\x18\x15 \x01(\v2\x15.redact.v3.RegexRulesH\x00R\x05regexB\b\n" +
	"\x06values\"H\n" +
	"\n" +
	"RegexRules\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12 \n" +
	"\vreplacement\x18\x02 \x01(\tR\vreplacement\"`\n" +
	"\fMessageRules\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\bR\x04skip\x12\x14\n" +
	"\x05empty\x18\x02 \x01(\bR\x05empty\x12\x10\n" +
	"\x03nil\x18\x03 \x01(\bR\x03nil\x12\x14\n" +
	"\x05apply\x18\x04 \x01(\bR\x05apply\"g\n" +
	"\fElementRules\x12\x14\n" +
	"\x05empty\x18\x01 \x01(\bR\x05empty\x12\x16\n" +
	"\x06nested\x18\x02 \x01(\bR\x06nested\x12)\n" +
	"\x04item\x18\x03 \x01(\v2\x15.redact.v3.FieldRulesR\x04item:;\n" +
	"\tfile_skip\x12\x1c.google.protobuf.FileOptions\x18\xf6\xbf\x05 \x01(\bR\bfileSkip:D\n" +
	"\fservice_skip\x12\x1f.google.protobuf.ServiceOptions\x18\xeb\xa6\x03 \x01(\bR\vserviceSkip:L\n" +
	"\x10internal_service\x12\x1f.google.protobuf.ServiceOptions\x18\xec\xa6\x03 \x01(\bR\x0finternalService:U\n" +
	"\x15internal_service_code\x12\x1f.google.protobuf.ServiceOptions\x18\xed\xa6\x03 \x01(\rR\x13internalServiceCode:b\n" +
	"\x1cinternal_service_err_message\x12\x1f.google.protobuf.ServiceOptions\x18\xee\xa6\x03 \x01(\tR\x19internalServiceErrMessage:A\n" +
	"\vmethod_skip\x12\x1e.google.protobuf.MethodOptions\x18\xeb\xa6\x03 \x01(\bR\n" +
	"methodSkip:I\n" +
	"\x0finternal_method\x12\x1e.google.protobuf.MethodOptions\x18\xec\xa6\x03 \x01(\bR\x0einternalMethod:R\n" +
	"\x14internal_method_code\x12\x1e.google.protobuf.MethodOptions\x18\xed\xa6\x03 \x01(\rR\x12internalMethodCode:_\n" +
	"\x1binternal_method_err_message\x12\x1e.google.protobuf.MethodOptions\x18\xee\xa6\x03 \x01(\tR\x18internalMethodErrMessage:3\n" +
	"\x03nil\x12\x1f.google.protobuf.MessageOptions\x18\xeb\xa6\x03 \x01(\bR\x03nil:7\n" +
	"\x05empty\x12\x1f.google.protobuf.MessageOptions\x18\xec\xa6\x03 \x01(\bR\x05empty:;\n" +
	"\aignored\x12\x1f.google.protobuf.MessageOptions\x18\xed\xa6\x03 \x01(\bR\aignored:L\n" +
	"\x05value\x12\x1d.google.protobuf.FieldOptions\x18\xeb\xa6\x03 \x01(\v2\x15.redact.v3.FieldRulesR\x05valueB:Z8github.com/menta2k/protoc-gen-redact/v3/redact/v3;redactb\x06proto3"

var (
	file_redact_v3_redact_proto_rawDescOnce sync.Once
	file_redact_v3_redact_proto_rawDescData []byte
)

func file_redact_v3_redact_proto_rawDescGZIP() []byte {
	file_redact_v3_redact_proto_rawDescOnce.Do(func() {
		file_redact_v3_redact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redact_v3_redact_proto_rawDesc), len(file_redact_v3_redact_proto_rawDesc)))
	})
	return file_redact_v3_redact_proto_rawDescData
}

var file_redact_v3_redact_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_redact_v3_redact_proto_goTypes = []any{
	(*FieldRules)(nil),                  // 0: redact.v3.FieldRules
	(*RegexRules)(nil),                  // 1: redact.v3.RegexRules
	(*MessageRules)(nil),                // 2: redact.v3.MessageRules
	(*ElementRules)(nil),                // 3: redact.v3.ElementRules
	(*descriptorpb.FileOptions)(nil),    // 4: google.protobuf.FileOptions
	(*descriptorpb.ServiceOptions)(nil), // 5: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 6: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 7: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 8: google.protobuf.FieldOptions
}
var file_redact_v3_redact_proto_depIdxs = []int32{
	2,  // 0: redact.v3.FieldRules.message:type_name -> redact.v3.MessageRules
	3,  // 1: redact.v3.FieldRules.element:type_name -> redact.v3.ElementRules
	1,  // 2: redact.v3.FieldRules.regex:type_name -> redact.v3.RegexRules
	0,  // 3: redact.v3.ElementRules.item:type_name -> redact.v3.FieldRules
	4,  // 4: redact.v3.file_skip:extendee -> google.protobuf.FileOptions
	5,  // 5: redact.v3.service_skip:extendee -> google.protobuf.ServiceOptions
	5,  // 6: redact.v3.internal_service:extendee -> google.protobuf.ServiceOptions
	5,  // 7: redact.v3.internal_service_code:extendee -> google.protobuf.ServiceOptions
	5,  // 8: redact.v3.internal_service_err_message:extendee -> google.protobuf.ServiceOptions
	6,  // 9: redact.v3.method_skip:extendee -> google.protobuf.MethodOptions
	6,  // 10: redact.v3.internal_method:extendee -> google.protobuf.MethodOptions
	6,  // 11: redact.v3.internal_method_code:extendee -> google.protobuf.MethodOptions
	6,  // 12: redact.v3.internal_method_err_message:extendee -> google.protobuf.MethodOptions
	7,  // 13: redact.v3.nil:extendee -> google.protobuf.MessageOptions
	7,  // 14: redact.v3.empty:extendee -> google.protobuf.MessageOptions
	7,  // 15: redact.v3.ignored:extendee -> google.protobuf.MessageOptions
	8,  // 16: redact.v3.value:extendee -> google.protobuf.FieldOptions
	0,  // 17: redact.v3.value:type_name -> redact.v3.FieldRules
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	17, // [17:18] is the sub-list for extension type_name
	4,  // [4:17] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_redact_v3_redact_proto_init() }
func file_redact_v3_redact_proto_init() {
	if File_redact_v3_redact_proto != nil {
		return
	}
	file_redact_v3_redact_proto_msgTypes[0].OneofWrappers = []any{
		(*FieldRules_Float)(nil),
		(*FieldRules_Double)(nil),
		(*FieldRules_Int32)(nil),
		(*FieldRules_Int64)(nil),
		(*FieldRules_Uint32)(nil),
		(*FieldRules_Uint64)(nil),
		(*FieldRules_Sint32)(nil),
		(*FieldRules_Sint64)(nil),
		(*FieldRules_Fixed32)(nil),
		(*FieldRules_Fixed64)(nil),
		(*FieldRules_Sfixed32)(nil),
		(*FieldRules_Sfixed64)(nil),
		(*FieldRules_Bool)(nil),
		(*FieldRules_String_)(nil),
		(*FieldRules_Bytes)(nil),
		(*FieldRules_Enum)(nil),
		(*FieldRules_Message)(nil),
		(*FieldRules_Element)(nil),
		(*FieldRules_Regex)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redact_v3_redact_proto_rawDesc), len(file_redact_v3_redact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 13,
			NumServices:   0,
		},
		GoTypes:           file_redact_v3_redact_proto_goTypes,
		DependencyIndexes: file_redact_v3_redact_proto_depIdxs,
		MessageInfos:      file_redact_v3_redact_proto_msgTypes,
		ExtensionInfos:    file_redact_v3_redact_proto_extTypes,
	}.Build()
	File_redact_v3_redact_proto = out.File
	file_redact_v3_redact_proto_goTypes = nil
	file_redact_v3_redact_proto_depIdxs = nil
}
