// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';
import {generator} from '../models';
import {configexporter} from '../models';
import {database} from '../models';
import {detect} from '../models';

export function AIFindOpenAPIFiles():Promise<ai.OpenAPIResult>;

export function AIGenerateBackendCode(arg1:string,arg2:string,arg3:Array<ai.MicroservicePartition>):Promise<string>;

export function AIGenerateDDL(arg1:string):Promise<ai.StepResult>;

export function AIPartitionMicroservices(arg1:string):Promise<ai.PartitionResult>;

export function AIReviewCode(arg1:Record<string, string>):Promise<ai.StepResult>;

export function CleanConfig():Promise<void>;

export function EditGeneratorOption(arg1:generator.Option):Promise<void>;

export function ExportConfigToRemote(arg1:configexporter.RemoteConfig):Promise<configexporter.ExportResult>;

export function ExportOneServiceConfig(arg1:configexporter.RemoteConfig,arg2:string):Promise<configexporter.ExportResult>;

export function GenerateFrontendCode(arg1:string,arg2:string):Promise<string>;

export function GenerateGrpcCode(arg1:string):Promise<string>;

export function GenerateRestCode(arg1:string):Promise<string>;

export function GetAIConfig():Promise<ai.Config>;

export function GetAIProviderPresets():Promise<Array<ai.AIProviderPreset>>;

export function GetConfigServices():Promise<Array<configexporter.ServiceInfo>>;

export function GetDBConfig():Promise<database.DBConfig>;

export function GetDatabaseTables(arg1:database.DBConfig):Promise<Array<database.TableInfo>>;

export function GetGeneratorOptions():Promise<Array<generator.Option>>;

export function GetProjectInfo():Promise<detect.ProjectInfo>;

export function GetRemoteConfigTypes():Promise<Array<Record<string, string>>>;

export function GetTableColumns(arg1:database.DBConfig,arg2:string):Promise<Array<database.ColumnInfo>>;

export function ImportDatabaseTables(arg1:database.DBConfig):Promise<string>;

export function ImportSqlTables(arg1:string):Promise<string>;

export function OpenProject(arg1:string):Promise<detect.ProjectInfo>;

export function SelectFolder():Promise<string>;

export function SetAIConfig(arg1:ai.Config):Promise<void>;

export function SetDBConfig(arg1:database.DBConfig):Promise<void>;

export function SetGeneratorOption(arg1:generator.GeneratorOptions):Promise<void>;

export function TestAIConnection():Promise<ai.StepResult>;

export function TestDatabaseConnection(arg1:database.DBConfig):Promise<database.ConnectionResult>;
