// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIFindOpenAPIFiles() {
  return window['go']['main']['App']['AIFindOpenAPIFiles']();
}

export function AIGenerateBackendCode(arg1, arg2, arg3) {
  return window['go']['main']['App']['AIGenerateBackendCode'](arg1, arg2, arg3);
}

export function AIGenerateDDL(arg1) {
  return window['go']['main']['App']['AIGenerateDDL'](arg1);
}

export function AIPartitionMicroservices(arg1) {
  return window['go']['main']['App']['AIPartitionMicroservices'](arg1);
}

export function AIReviewCode(arg1) {
  return window['go']['main']['App']['AIReviewCode'](arg1);
}

export function AddService(arg1) {
  return window['go']['main']['App']['AddService'](arg1);
}

export function CleanConfig() {
  return window['go']['main']['App']['CleanConfig']();
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DevBufGenerate() {
  return window['go']['main']['App']['DevBufGenerate']();
}

export function DevEntGenerate(arg1) {
  return window['go']['main']['App']['DevEntGenerate'](arg1);
}

export function DevGoModTidy() {
  return window['go']['main']['App']['DevGoModTidy']();
}

export function DevRunService(arg1) {
  return window['go']['main']['App']['DevRunService'](arg1);
}

export function DevWireGenerate(arg1) {
  return window['go']['main']['App']['DevWireGenerate'](arg1);
}

export function EditGeneratorOption(arg1) {
  return window['go']['main']['App']['EditGeneratorOption'](arg1);
}

export function ExportConfigToRemote(arg1) {
  return window['go']['main']['App']['ExportConfigToRemote'](arg1);
}

export function ExportOneServiceConfig(arg1, arg2) {
  return window['go']['main']['App']['ExportOneServiceConfig'](arg1, arg2);
}

export function GenerateFrontendCode(arg1, arg2) {
  return window['go']['main']['App']['GenerateFrontendCode'](arg1, arg2);
}

export function GenerateGrpcCode(arg1) {
  return window['go']['main']['App']['GenerateGrpcCode'](arg1);
}

export function GenerateRestCode(arg1) {
  return window['go']['main']['App']['GenerateRestCode'](arg1);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetAIProviderPresets() {
  return window['go']['main']['App']['GetAIProviderPresets']();
}

export function GetConfigServices() {
  return window['go']['main']['App']['GetConfigServices']();
}

export function GetDBConfig() {
  return window['go']['main']['App']['GetDBConfig']();
}

export function GetDatabaseTables(arg1) {
  return window['go']['main']['App']['GetDatabaseTables'](arg1);
}

export function GetDevServices() {
  return window['go']['main']['App']['GetDevServices']();
}

export function GetGeneratorOptions() {
  return window['go']['main']['App']['GetGeneratorOptions']();
}

export function GetProjectInfo() {
  return window['go']['main']['App']['GetProjectInfo']();
}

export function GetRemoteConfigTypes() {
  return window['go']['main']['App']['GetRemoteConfigTypes']();
}

export function GetTableColumns(arg1, arg2) {
  return window['go']['main']['App']['GetTableColumns'](arg1, arg2);
}

export function ImportDatabaseTables(arg1) {
  return window['go']['main']['App']['ImportDatabaseTables'](arg1);
}

export function ImportSqlTables(arg1) {
  return window['go']['main']['App']['ImportSqlTables'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetAIConfig(arg1) {
  return window['go']['main']['App']['SetAIConfig'](arg1);
}

export function SetDBConfig(arg1) {
  return window['go']['main']['App']['SetDBConfig'](arg1);
}

export function SetGeneratorOption(arg1) {
  return window['go']['main']['App']['SetGeneratorOption'](arg1);
}

export function TestAIConnection() {
  return window['go']['main']['App']['TestAIConnection']();
}

export function TestDatabaseConnection(arg1) {
  return window['go']['main']['App']['TestDatabaseConnection'](arg1);
}
