// protoc-gen-wind-errors generates WindError-typed error helpers from proto
// enums annotated with the kratos-style (errors.code) / (errors.default_code)
// options. It is the wind counterpart of the kratos protoc-gen-go-errors
// output: same input protos, same file naming, same IsXxx/ErrorXxx shapes —
// but the helpers produce *windErrors.WindError instead of kratos *errors.Error.
//
// 生成契约：
//   - (errors.code) 注解的是 HTTP 状态码，直写 WindError.Code，由
//     go-wind/errors 的 CodeToHTTP 400-599 直通段在传输层原样复现——
//     与 v1 kratos 产物（errors.New(code,…) 的 code 即 HTTP 状态）契约一致。
//   - ErrorXxx(format, args…) 的格式化文案经 WithCause 挂入错误链：
//     日志可读（Error() 含 cause），线上响应体保持 {reason, details}，
//     后端 message 不出网（前端仅按 reason 本地化）。
//   - 扩展值用 protowire 从 options 原始字节读取（字段号 1108/1109），
//     本生成器不链接 kratos 模块。
package main

import (
	"flag"
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"
)

// release is the current protoc-gen-wind-errors version.
const release = "v0.1.0"

// Extension field numbers declared in errors/errors.proto
// (github.com/go-kratos/kratos/v2/errors; protoc consumes it via the
// buf.build/kratos/apis dependency).
const (
	enumDefaultCodeFieldNum protowire.Number = 1108 // errors.default_code → google.protobuf.EnumOptions
	enumValueCodeFieldNum   protowire.Number = 1109 // errors.code → google.protobuf.EnumValueOptions
)

var showVersion = flag.Bool("version", false, "print the version and exit")

func main() {
	flag.Parse()
	if *showVersion {
		fmt.Printf("protoc-gen-wind-errors %v\n", release)
		return
	}
	protogen.Options{
		ParamFunc: flag.CommandLine.Set,
	}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

// errorEnum pairs an enum with its resolved per-value codes
// (explicit errors.code, else the enum's errors.default_code, else 0).
type errorEnum struct {
	enum  *protogen.Enum
	codes map[protoreflect.EnumNumber]int32
}

// generateFile emits <prefix>_errors.pb.go when the file contains at least one
// error enum. An enum counts as an error enum when the enum itself carries
// errors.default_code or any of its values carries errors.code — files with
// ordinary (non-error) enums produce no output.
func generateFile(gen *protogen.Plugin, f *protogen.File) {
	var enums []*errorEnum
	for _, e := range f.Enums {
		if ee := newErrorEnum(e); ee != nil {
			enums = append(enums, ee)
		}
	}
	for _, m := range f.Messages {
		enums = appendEnumsFromMessage(enums, m)
	}
	if len(enums) == 0 {
		return
	}

	g := gen.NewGeneratedFile(f.GeneratedFilenamePrefix+"_errors.pb.go", f.GoImportPath)
	g.P("// Code generated by protoc-gen-wind-errors. DO NOT EDIT.")
	g.P()
	g.P("package ", f.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	fmt "fmt"`)
	g.P()
	g.P(`	windErrors "github.com/tx7do/go-wind/errors"`)
	g.P(")")
	g.P()

	for _, ee := range enums {
		for _, v := range ee.enum.Values {
			code := ee.codes[v.Desc.Number()]
			name := camelCase(string(v.Desc.Name()))
			emitIsFunc(g, v, name, code)
			g.P()
			emitErrorFunc(g, v, name, code)
			g.P()
		}
	}
}

func appendEnumsFromMessage(acc []*errorEnum, m *protogen.Message) []*errorEnum {
	for _, e := range m.Enums {
		if ee := newErrorEnum(e); ee != nil {
			acc = append(acc, ee)
		}
	}
	for _, nested := range m.Messages {
		acc = appendEnumsFromMessage(acc, nested)
	}
	return acc
}

// newErrorEnum returns nil when the enum carries no error annotation at all.
func newErrorEnum(e *protogen.Enum) *errorEnum {
	defaultCode, hasDefault := optionVarint(e.Desc.Options(), enumDefaultCodeFieldNum)
	ee := &errorEnum{enum: e, codes: make(map[protoreflect.EnumNumber]int32, len(e.Values))}
	hasAny := false
	for _, v := range e.Values {
		code, ok := optionVarint(v.Desc.Options(), enumValueCodeFieldNum)
		if ok {
			hasAny = true
		} else {
			code = defaultCode
		}
		ee.codes[v.Desc.Number()] = code
	}
	if !hasDefault && !hasAny {
		return nil
	}
	return ee
}

func emitIsFunc(g *protogen.GeneratedFile, v *protogen.EnumValue, name string, code int32) {
	emitValueComment(g, v)
	g.P("func Is", name, "(err error) bool {")
	g.P("	if err == nil {")
	g.P("		return false")
	g.P("	}")
	g.P("	e, ok := windErrors.FromError(err)")
	g.P("	return ok && e.Reason == ", g.QualifiedGoIdent(v.GoIdent), ".String() && e.Code == ", code)
	g.P("}")
}

func emitErrorFunc(g *protogen.GeneratedFile, v *protogen.EnumValue, name string, code int32) {
	emitValueComment(g, v)
	g.P("func Error", name, "(format string, args ...interface{}) *windErrors.WindError {")
	g.P("	return windErrors.New(", code, ", ", g.QualifiedGoIdent(v.GoIdent), ".String()).WithCause(fmt.Errorf(format, args...))")
	g.P("}")
}

func emitValueComment(g *protogen.GeneratedFile, v *protogen.EnumValue) {
	leading := strings.TrimSuffix(string(v.Comments.Leading), "\n")
	if leading == "" {
		return
	}
	for _, line := range strings.Split(leading, "\n") {
		g.P("//", line)
	}
}

// camelCase converts an enum value name (SNAKE_CASE) to the exported Go
// identifier segment, matching the kratos generator's convention:
// URI_TOO_LONG → UriTooLong, IM_A_TEAPOT → ImATeapot.
func camelCase(name string) string {
	parts := strings.Split(name, "_")
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(strings.ToLower(part[1:]))
	}
	return b.String()
}

// optionVarint extracts an int32 custom-option value from the raw options
// bytes by field number, without linking the extension's Go type. Custom
// options unknown to this binary stay in the options message's unknown
// fields, where protowire can read them directly.
func optionVarint(opts proto.Message, fieldNum protowire.Number) (int32, bool) {
	if opts == nil || !opts.ProtoReflect().IsValid() {
		return 0, false
	}
	b := opts.ProtoReflect().GetUnknown()
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return 0, false
		}
		b = b[n:]
		if num == fieldNum && typ == protowire.VarintType {
			val, m := protowire.ConsumeVarint(b)
			if m < 0 {
				return 0, false
			}
			return int32(val), true
		}
		m := protowire.ConsumeFieldValue(num, typ, b)
		if m < 0 {
			return 0, false
		}
		b = b[m:]
	}
	return 0, false
}
