package plugin

import (
	"github.com/tx7do/go-wind-toolkit/protoc-gen-typescript-http/internal/codegen"
	"github.com/tx7do/go-wind-toolkit/protoc-gen-typescript-http/internal/protowalk"
	"google.golang.org/protobuf/reflect/protoreflect"
)

type packageGenerator struct {
	pkg   protoreflect.FullName
	files []protoreflect.FileDescriptor
}

func (p packageGenerator) Generate(f *codegen.File) error {
	p.generateHeader(f)
	defaultHost := p.readDefaultHost()
	generateTransportInfra(f, defaultHost)
	var walkErr error
	var services []protoreflect.ServiceDescriptor
	protowalk.WalkFiles(p.files, func(desc protoreflect.Descriptor) bool {
		if wkt, ok := WellKnownType(desc); ok {
			f.P(wkt.TypeDeclaration())
			return false
		}
		switch v := desc.(type) {
		case protoreflect.MessageDescriptor:
			if v.IsMapEntry() {
				return false
			}
			messageGenerator{pkg: p.pkg, message: v}.Generate(f)
		case protoreflect.EnumDescriptor:
			enumGenerator{pkg: p.pkg, enum: v}.Generate(f)
		case protoreflect.ServiceDescriptor:
			services = append(services, v)
			if err := (serviceGenerator{
				pkg:     p.pkg,
				service: v,
			}).Generate(f); err != nil {
				walkErr = err
				return false
			}
		}
		return true
	})
	if walkErr != nil {
		return walkErr
	}
	// Generate the unified ApiClient after all individual service clients.
	generateApiClient(f, services)
	return nil
}

func (p packageGenerator) readDefaultHost() string {
	var firstHost string
	var firstService string
	for _, file := range p.files {
		services := file.Services()
		for i := 0; i < services.Len(); i++ {
			svc := services.Get(i)
			host := getDefaultHost(svc)
			if host == "" {
				continue
			}
			if firstHost == "" {
				firstHost = host
				firstService = string(svc.FullName())
			} else if host != firstHost {
				Warn("service %s has default_host %q but service %s already set %q; using the first one", svc.FullName(), host, firstService, firstHost)
			}
		}
	}
	return firstHost
}

func (p packageGenerator) generateHeader(f *codegen.File) {
	f.P("// Code generated by protoc-gen-typescript-http. DO NOT EDIT.")
	f.P("/* eslint-disable no-use-before-define, @typescript-eslint/no-unused-vars, prettier/prettier */")
	f.P("// @ts-nocheck: generated code does not require type checking")
	f.P()
}
