package plugin

import (
	"github.com/tx7do/go-wind-toolkit/protoc-gen-typescript-http/internal/codegen"
	"github.com/tx7do/go-wind-toolkit/protoc-gen-typescript-http/internal/protowalk"
	"google.golang.org/protobuf/reflect/protoreflect"
)

type packageGenerator struct {
	pkg   protoreflect.FullName
	files []protoreflect.FileDescriptor
}

func (p packageGenerator) Generate(f *codegen.File) error {
	p.generateHeader(f)
	defaultHost := p.readDefaultHost()
	generateTransportInfra(f, defaultHost)
	var walkErr error
	protowalk.WalkFiles(p.files, func(desc protoreflect.Descriptor) bool {
		if wkt, ok := WellKnownType(desc); ok {
			f.P(wkt.TypeDeclaration())
			return false
		}
		switch v := desc.(type) {
		case protoreflect.MessageDescriptor:
			if v.IsMapEntry() {
				return false
			}
			messageGenerator{pkg: p.pkg, message: v}.Generate(f)
		case protoreflect.EnumDescriptor:
			enumGenerator{pkg: p.pkg, enum: v}.Generate(f)
		case protoreflect.ServiceDescriptor:
			if err := (serviceGenerator{
				pkg:     p.pkg,
				service: v,
			}).Generate(f); err != nil {
				walkErr = err
				return false
			}
		}
		return true
	})
	if walkErr != nil {
		return walkErr
	}
	return nil
}

func (p packageGenerator) readDefaultHost() string {
	for _, file := range p.files {
		services := file.Services()
		for i := 0; i < services.Len(); i++ {
			if host := getDefaultHost(services.Get(i)); host != "" {
				return host
			}
		}
	}
	return ""
}

func (p packageGenerator) generateHeader(f *codegen.File) {
	f.P("// Code generated by protoc-gen-typescript-http. DO NOT EDIT.")
	f.P("/* eslint-disable camelcase */")
	f.P("// @ts-nocheck")
	f.P()
}
